CSharpMVC/SlnDndInfoWebsite/src/Devs2Blu.ProjetosAula.DndInfoWebsite/Models/AbilityScores.cs
namespace Devs2Blu.ProjetosAula.DndInfoWebsite.Models
{
    public class AbilityScores
    {
        public string Index { get; set; }

    }
}

CSharpMVC/SlnDndInfoWebsite/src/Devs2Blu.ProjetosAula.DndInfoWebsite/Models/ErrorViewModel.cs
namespace Devs2Blu.ProjetosAula.DndInfoWebsite.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CSharpMVC/SlnDndInfoWebsite/src/Devs2Blu.ProjetosAula.DndInfoWebsite/Controllers/DndController.cs
using Microsoft.AspNetCore.Mvc;

namespace Devs2Blu.ProjetosAula.DndInfoWebsite.Controllers
{
    public class DndController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AbilityScores()
        {
            return View();
        }
    }
}

CSharpMVC/SlnDndInfoWebsite/src/Devs2Blu.ProjetosAula.DndInfoWebsite/Controllers/HomeController.cs
using Devs2Blu.ProjetosAula.DndInfoWebsite.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Devs2Blu.ProjetosAula.DndInfoWebsite.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CSharpMVC/SlnDndInfoWebsite/src/Devs2Blu.ProjetosAula.DndInfoWebsite/Views/Dnd/AbilityScores.cshtml
@{
    ViewData["Title"] = "Ability scores";
}

<div>
    foreach(var result in Model.results){

    }

</div>

CSharpMVC/SlnDndInfoWebsite/src/Devs2Blu.ProjetosAula.DndInfoWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Category Index";
}
 @*  {
"ability-scores": "/api/ability-scores",
"alignments": "/api/alignments",
"backgrounds": "/api/backgrounds",
"classes": "/api/classes",
"conditions": "/api/conditions",
"damage-types": "/api/damage-types",
"equipment": "/api/equipment",
"equipment-categories": "/api/equipment-categories",
"feats": "/api/feats",
"features": "/api/features",
"languages": "/api/languages",
"magic-items": "/api/magic-items",
"magic-schools": "/api/magic-schools",
"monsters": "/api/monsters",
"proficiencies": "/api/proficiencies",
"races": "/api/races",
"rule-sections": "/api/rule-sections",
"rules": "/api/rules",
"skills": "/api/skills",
"spells": "/api/spells",
"subclasses": "/api/subclasses",
"subraces": "/api/subraces",
"traits": "/api/traits",
"weapon-properties": "/api/weapon-properties"
}*@
<div class="container bg-trans-brown text-center p-3 align-content-center">
    <h2>Index of informational pages</h2>
    <div class="row">
            <a class="text-light" asp-area="" asp-controller="Dnd" asp-action="AbilityScores">Ability Scores</a>
        </div>
        <div class="row">
            <p class="text-light">Races</p>
        </div>
        <div class="row">
            <p class="text-light">Classes</p>
        </div>
        <div class="row">
            <p class="text-light">Spells</p>
        </div>
</div>